// =============================================================================
// MPCG Top-Level Testbench (Interface Stub)
// Reads test vectors generated by gen_test_vectors.py
// Drives RTL with membrane potential inputs, compares outputs to Python reference
// =============================================================================
// NOTE: Stimulus generation and verification logic removed for IP protection.
//       This file provides the DUT instantiation template and parameter
//       definitions for reference. Contact the authors for the full testbench.
// =============================================================================

`include "defines.vh"

`timescale 1ns / 1ps

module tb_mpcg_top;

    // Clock and reset
    reg clk;
    reg rst_n;

    // DUT signals
    reg                                mode_train;
    reg                                warmup;
    reg                                valid_in;
    reg  [NUM_CLASSES*DATA_WIDTH-1:0]  v_in;

    wire                               weight_valid;
    wire [DATA_WIDTH-1:0]              weight;
    wire                               pred_valid;
    wire [3:0]                         pred_class;
    wire [DATA_WIDTH-1:0]              pred_conf;
    wire [DATA_WIDTH-1:0]              theta_out;
    wire [DATA_WIDTH-1:0]              mpcg_conf;

    // Test parameters
    localparam NUM_SAMPLES    = 100;
    localparam VEC_PER_SAMPLE = TIMESTEPS * NUM_CLASSES;
    localparam REF_PER_SAMPLE = 3;

    // Clock generation: 100 MHz
    initial clk = 0;
    always #5 clk = ~clk;

    // DUT instantiation
    mpcg_top u_dut (
        .clk         (clk),
        .rst_n       (rst_n),
        .mode_train  (mode_train),
        .warmup      (warmup),
        .valid_in    (valid_in),
        .v_in        (v_in),
        .weight_valid(weight_valid),
        .weight      (weight),
        .pred_valid  (pred_valid),
        .pred_class  (pred_class),
        .pred_conf   (pred_conf),
        .theta_out   (theta_out),
        .mpcg_conf   (mpcg_conf)
    );

    // Stimulus & Verification (removed for IP protection)
    // The full testbench:
    //   1. Loads test_vectors_input.mem and test_vectors_ref.mem
    //   2. Drives T=4 timesteps of membrane potentials per sample
    //   3. Compares MPCG confidence, predicted class, and DNLP weight
    //   4. Reports pass/fail with error statistics
    //
    // Contact the authors for the full implementation.

    initial begin
        $display("ERROR: This is an interface stub. Full testbench not included.");
        $display("       Contact the authors for the complete verification suite.");
        $finish;
    end

endmodule
