// =============================================================================
// Block 3a: Sigmoid LUT
// Approximates sigma(k * (mpcg_n - theta)) via 256-entry lookup table
// k=5 is pre-baked into the LUT (generated by gen_lut.py)
// Input:  delta = mpcg_n - theta (signed Q8.8)
// Output: sigmoid value (unsigned Q8.8, range [0, 1.0])
// =============================================================================

`include "defines.vh"

module sigmoid_lut (
    input  wire                  clk,
    input  wire                  rst_n,
    input  wire                  valid_in,
    input  wire [DATA_WIDTH-1:0] mpcg_n,     // MPCG confidence (Q8.8)
    input  wire [DATA_WIDTH-1:0] theta,       // adaptive threshold (Q8.8)
    output reg                   valid_out,
    output reg  [DATA_WIDTH-1:0] sigmoid_val  // sigma(5*(mpcg_n - theta)) (Q8.8)
);

    // =========================================================================
    // Implementation removed for IP protection.
    // Contact the authors for the full implementation.
    // =========================================================================

    // Tie off outputs (stub only - not functional)
    assign valid_out = 1'b0;
    assign sigmoid_val = {DATA_WIDTH{1'b0}};

endmodule
