# =============================================================================
# Vivado Project Creation and Synthesis Script
# Target: Xilinx Zynq-7000 xc7z020clg400-1
# Usage: vivado -mode batch -source project.tcl
# =============================================================================

# Project settings
set project_name "mpcg_synth"
set project_dir  "./vivado_project"
set part_name    "xc7z020clg400-1"
set top_module   "mpcg_top"

# Create project
create_project $project_name $project_dir -part $part_name -force

# Add RTL sources
add_files [glob ../src/*.v]
add_files [glob ../src/*.vh]

# Add constraint file
add_files -fileset constrs_1 constraints.xdc

# Add LUT initialization files (generated by gen_lut.py)
add_files ../scripts/softmax_lut.mem
add_files ../scripts/sigmoid_lut.mem

# Set top module
set_property top $top_module [current_fileset]

# Set Verilog include directories
set_property verilog_define {} [current_fileset]
set_property include_dirs {../src} [current_fileset]

# Update compile order
update_compile_order -fileset sources_1

# =============================================================================
# Synthesis
# =============================================================================
puts "=== Starting Synthesis ==="

# Synthesis settings
set_property strategy Flow_PerfOptimized_high [get_runs synth_1]
set_property STEPS.SYNTH_DESIGN.ARGS.DIRECTIVE AreaOptimized_high [get_runs synth_1]

launch_runs synth_1 -jobs 4
wait_on_run synth_1

# Check synthesis status
if {[get_property STATUS [get_runs synth_1]] != "synth_design Complete!"} {
    puts "ERROR: Synthesis failed!"
    exit 1
}
puts "=== Synthesis Complete ==="

# Generate post-synthesis reports
open_run synth_1
report_utilization -file ${project_dir}/synth_utilization.txt
report_timing_summary -file ${project_dir}/synth_timing.txt

# =============================================================================
# Implementation (Place & Route)
# =============================================================================
puts "=== Starting Implementation ==="

launch_runs impl_1 -jobs 4
wait_on_run impl_1

if {[get_property STATUS [get_runs impl_1]] != "route_design Complete!"} {
    puts "ERROR: Implementation failed!"
    exit 1
}
puts "=== Implementation Complete ==="

# =============================================================================
# Post-Implementation Reports
# =============================================================================
open_run impl_1

# Utilization report (LUT, FF, BRAM, DSP)
report_utilization -file ${project_dir}/impl_utilization.txt
report_utilization -hierarchical -file ${project_dir}/impl_utilization_hier.txt

# Timing report
report_timing_summary -file ${project_dir}/impl_timing.txt
report_timing -max_paths 10 -file ${project_dir}/impl_timing_detail.txt

# Power report (with switching activity estimation)
set_switching_activity -toggle_rate 12.5 -static_probability 0.5 [get_nets *]
report_power -file ${project_dir}/impl_power.txt

# Design statistics
report_design_analysis -file ${project_dir}/design_analysis.txt

# =============================================================================
# Summary
# =============================================================================
puts ""
puts "========================================"
puts "MPCG FPGA Synthesis Complete"
puts "========================================"
puts "Target: $part_name"
puts "Top:    $top_module"
puts ""
puts "Reports saved to: $project_dir/"
puts "  - synth_utilization.txt"
puts "  - impl_utilization.txt"
puts "  - impl_utilization_hier.txt"
puts "  - impl_timing.txt"
puts "  - impl_power.txt"
puts "========================================"

exit 0
